config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_config.fish:
    dst: ~/.config/fish/config.fish
    src: config/fish/config.fish
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
profiles:
  aweidner-mbp:
    dotfiles:
      - f_config.fish
      - f_init.vim
  base:
    dotfiles:
      - f_config.fish
      - f_init.vim
